metamodel:
  name: botecopro
  version: 1.0.0
  source: schema
  default_schema: public
  dialects:
    - sqlite
    - sqlite
  generated_targets:
    - sql
    - python
    - dart
  conventions:
    pk_name: id
    timestamp_default: now()
